apiVersion: v1
kind: Service
metadata:
  name: {{ include "stolon.proxy.fullname" . }}
  labels:
    {{- include "stolon.proxy.labels" . | nindent 4 }}
  {{- with .Values.proxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.proxy.service.type }}
  {{- if and (eq .Values.proxy.service.type "LoadBalancer") (not (empty .Values.proxy.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.proxy.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    {{- include "stolon.proxy.selectorLabels" . | nindent 4 }}
