apiVersion: v1
kind: Service
metadata:
  name: {{ include "stolon.proxy.fullname" . }}
  labels:
    {{- include "stolon.proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    {{- include "stolon.proxy.selectorLabels" . | nindent 4 }}
