{{- if .Values.exporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stolon.exporter.fullname" . }}
  labels:
    {{- include "stolon.exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.exporter.replicaCount }}
  selector:
    matchLabels:
      {{- include "stolon.exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stolon.exporter.selectorLabels" . | nindent 8 }}
      {{- with .Values.exporter.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.exporter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.exporter.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  {{- include "stolon.exporter.selectorLabels" . | nindent 18 }}
              topologyKey: kubernetes.io/hostname
            weight: 1
      {{- end }}
      {{- with .Values.exporter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: exporter
        image: {{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}
        imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
        args:
        {{- if .Values.exporter.disableDefaultMetrics }}
        - "--disable-default-metrics"
        {{- end }}
        {{- if .Values.exporter.disableSettingsMetrics }}
        - "--disable-settings-metrics"
        {{- end }}
        env:
        {{- if .Values.exporter.datasourceSecret }}
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.exporter.datasourceSecret.name }}
              key: {{ .Values.exporter.datasourceSecret.key }}
        {{- else }}
        - name: DATA_SOURCE_URI
          value: {{ template "prometheus-postgres-exporter.data_source_uri" . }}
        - name: DATA_SOURCE_USER
          value: {{ .Values.exporter.datasource.user }}
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: {{ include "stolon.fullname" . }}
              key: auth-superuser-password
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.exporter.service.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          {{- toYaml .Values.exporter.resources | nindent 10 }}
{{- end }}