apiVersion: v1
kind: Service
metadata:
  name: {{ include "stolon.keeper.fullname" . }}
  labels:
    {{- include "stolon.keeper.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  {{- if .Values.exporter.enabled }}
  - name: exporter
    port: 9187
    targetPort: exporter
  {{- end }}
  selector:
    {{- include "stolon.keeper.selectorLabels" . | nindent 4 }}
