---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stolon.fullname" . }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
type: Opaque
data:
  auth-superuser-password: {{ .Values.auth.superuser.password | b64enc }}
  auth-replication-password: {{ .Values.auth.replication.password | b64enc }}
